import { DM_Sans, Lora } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { dark } from "@clerk/themes";
import Header from "@/components/Header";
import { Toaster } from "sonner";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/animate-ui/components/radix/accordion";
import Link from "next/link";


const lora=Lora({
  subsets:["latin"],
  weight:["400","500"],
  style:["normal","italic"],
  variable:"--font-serif"  
})

const dmSans=DM_Sans({
  subsets:["latin"],
  weight:["300","400","500","600"],
  variable:"--font-sans"
})


export const metadata = {
  title: "Prepflow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      theme:dark
    }}>
    <html lang="en" suppressHydrationWarning>
      <body className={`${lora.variable} ${dmSans.variable} font-sans`}>
         <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            forcedTheme="dark"
          >
          
       {/* Header */}
         <Header/>
       <main className="min-h-screen ">
          {children}
       </main>

       <Toaster richColors/>
      {/* Footer */}

      <footer className="relative z-10  border-white/10 py-12 px-10 bg-black">
  <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-12">
    
    {/* LEFT — Quick Links */}
    <div className="flex flex-col gap-8">
      
      {/* Brand */}
      <div>
       
        <p className="text-stone-400 text-sm leading-relaxed max-w-xs">
          AI-powered mock interviews with real feedback. Get ready for your dream job.
        </p>
      </div>

      {/* Links Grid */}
      
        {/* Page sections */}
        <div className="flex  gap-10 ">
          <div className="flex flex-col gap-2">
          <p className="text-white font-semibold text-sm mb-1">Quick Links</p>
          <Link
            href="/#home"
            scroll={true}
            className="text-stone-400 hover:text-white text-sm transition-colors"
          >
            Home
          </Link>
          <Link
            href="/#features"
            scroll={true}
            className="text-stone-400 hover:text-white text-sm transition-colors"
          >
            Features
          </Link>
          <Link
            href="/#about"
            scroll={true}
            className="text-stone-400 hover:text-white text-sm transition-colors"
          >
            About
          </Link>
           

          <Link
            href="/#pricing"
            scroll={true}
            className="text-stone-400 hover:text-white text-sm transition-colors"
          >
            Pricing
          </Link>
          <Link
            href="/#contact"
            scroll={true}
            className="text-stone-400 hover:text-white text-sm transition-colors"
          >
            Contact
          </Link>
        </div>
       
        

        

        {/* App pages */}
        <div className="flex flex-col gap-2">
          <p className="text-white font-semibold text-sm mb-1">Get Started</p>
          <Link href="/explore" className="text-stone-400 hover:text-white text-sm transition-colors">
            Explore Interviewers
          </Link>
          <Link href="/appointments" className="text-stone-400 hover:text-white text-sm transition-colors">
            My Appointments
          </Link>
          <Link href="/dashboard" className="text-stone-400 hover:text-white text-sm transition-colors">
            Dashboard
          </Link>
          
        </div>
        
        


        </div>
         {/* Connect with me */}
<section className="flex flex-col gap-2" id="contact">
 
  <div className="flex  gap-4">
    <a
      href="https://github.com/Balaji849"
      target="_blank"
      rel="noopener noreferrer"
      className="flex items-center gap-2 text-stone-400 hover:text-white text-sm transition-colors group"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="30"
        height="30"
        viewBox="0 0 24 24"
        fill="currentColor"
        className="group-hover:scale-110 transition-transform"
      >
        <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z" />
      </svg>
      GitHub
    </a>

    <a
      href="https://www.linkedin.com/in/balaji-m-06b1772a1/"
      target="_blank"
      rel="noopener noreferrer"
      className="flex items-center gap-2 text-stone-400 hover:text-white text-sm transition-colors group"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="30"
        height="30"
        viewBox="0 0 24 24"
        fill="currentColor"
        className="group-hover:scale-110 transition-transform"
      >
        <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 0 1-2.063-2.065 2.064 2.064 0 1 1 2.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
      </svg>
      LinkedIn
    </a>
  </div>
</section>


        
        
        

      
    </div>
    
    

    {/* RIGHT — FAQ Accordion */}
    <div>
      <p className="text-white font-semibold text-sm mb-4">Frequently Asked Questions</p>
      <Accordion type="single" collapsible className="w-full">

        <AccordionItem value="book-interview">
          <AccordionTrigger className="text-sm text-stone-300 ">
            How do I book an interview?
          </AccordionTrigger>
          <AccordionContent className="text-stone-400 text-sm">
            Go to <strong className="text-white">Explore</strong>, browse interviewers, 
            and click <strong className="text-white">Book Session</strong>. Pick a slot 
            and confirm.
          </AccordionContent>
        </AccordionItem>

        <AccordionItem value="conduct-interview">
          <AccordionTrigger className="text-sm text-stone-300">
            How do I conduct an interview?
          </AccordionTrigger>
          <AccordionContent className="text-stone-400 text-sm">
            Check your <strong className="text-white">Dashboard</strong> for upcoming 
            sessions. Join at the scheduled time and use PrepFlow's built-in 
            question bank to guide the interview.
          </AccordionContent>
        </AccordionItem>

        <AccordionItem value="answer-questions">
          <AccordionTrigger className="text-sm text-stone-300">
            How do I answer questions during a session?
          </AccordionTrigger>
          <AccordionContent className="text-stone-400 text-sm">
            Questions appear on screen one at a time during the call. 
            The interviewer takes live notes and you can ask for hints if allowed.
          </AccordionContent>
        </AccordionItem>

        <AccordionItem value="feedback">
          <AccordionTrigger className="text-sm text-stone-300">
            How does feedback work?
          </AccordionTrigger>
          <AccordionContent className="text-stone-400 text-sm">
            After the session, interviewers submit structured feedback on 
            <strong className="text-white"> communication</strong>, 
            <strong className="text-white"> technical skills</strong>, and 
            <strong className="text-white"> problem-solving</strong>. 
            Find it in your <strong className="text-white">Appointments</strong> tab.
          </AccordionContent>
        </AccordionItem>

        <AccordionItem value="credits">
          <AccordionTrigger className="text-sm text-stone-300">
            How do credits work?
          </AccordionTrigger>
          <AccordionContent className="text-stone-400 text-sm">
            Interviewees spend credits to book sessions. Interviewers earn 
            credits for conducting them. Top up anytime from your profile.
          </AccordionContent>
        </AccordionItem>

      </Accordion>
    </div>

  </div>
</footer>
        
      </ThemeProvider>
      
       </body>
    </html>
    </ClerkProvider>
  );
}
